"use client";

import { useState } from "react";
import { AlertCircle, ArrowUpRight, CalendarClock, FileSearch, Landmark, Sparkles } from "lucide-react";
import type { InvestigationReport } from "@/lib/types";
import { money, percent, titleCase } from "@/components/format";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Timeline } from "@/components/timeline";

const sections = ["Overview", "Cases", "Recommendations", "Executive report", "Timeline"] as const;
type Section = (typeof sections)[number];

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) {
  return <Card className="border border-slate-100 p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold tracking-tight text-ink">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></Card>;
}

export function ReportDashboard({ report }: { report: InvestigationReport }) {
  const [section, setSection] = useState<Section>("Overview");
  const limitations = report.executive_summary?.limitations ?? ["No executive report limitations are available."];
  return <div>
    <div className="flex flex-col justify-between gap-5 border-b border-slate-200 pb-7 md:flex-row md:items-end"><div><div className="flex flex-wrap items-center gap-2"><Badge tone="mint">{titleCase(report.status)}</Badge><span className="font-mono text-xs text-slate-500">{report.investigation_id}</span></div><h1 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Investigation dashboard</h1><p className="mt-2 max-w-2xl leading-7 text-slate-600">A completed, traceable view of the financial signals in this case.</p></div><div className="flex flex-wrap gap-1 rounded-xl bg-slate-100 p-1">{sections.map((item) => <button key={item} onClick={() => setSection(item)} className={`rounded-lg px-3 py-2 text-sm font-semibold transition ${section === item ? "bg-white text-ink shadow-sm" : "text-slate-600 hover:bg-white/70"}`}>{item}</button>)}</div></div>
    {section === "Overview" && <div className="mt-8 space-y-7"><div className="grid gap-4 md:grid-cols-3"><Metric label="Monthly exposure" value={money(report.estimated_monthly_loss)} detail="Aggregate of case-level estimates" /><Metric label="Annualized exposure" value={money(report.estimated_annual_loss)} detail="Monthly estimate × 12" /><Metric label="Evidence confidence" value={percent(report.confidence)} detail="Last deterministic investigator confidence" /></div><Card className="border border-slate-100"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50"><Landmark className="text-emerald-600" size={20} /></span><div><p className="font-bold">Selected investigation plan</p><p className="text-sm text-slate-600">The planner chose these scopes from uploaded dataset metadata.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-5">{report.investigation_plan.map((item) => <div key={item.investigator} className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Priority {item.priority}</p><p className="mt-1 text-sm font-bold">{titleCase(item.investigator)}</p><div className="mt-2"><Badge tone={item.status === "completed" ? "mint" : "amber"}>{titleCase(item.status)}</Badge></div></div>)}</div></Card><Card className="border border-amber-100 bg-gradient-to-br from-amber-50/50 to-white"><div className="flex items-center gap-3"><Sparkles className="text-amber-500" /><div><p className="font-bold">Executive headline</p><p className="mt-1 text-lg font-semibold">{report.executive_summary?.headline ?? "Executive synthesis is unavailable."}</p></div></div><p className="mt-4 leading-7 text-slate-600">{report.executive_summary?.summary}</p></Card></div>}
    {section === "Cases" && <div className="mt-7 grid gap-5">{report.case_files.map((caseFile) => <Card key={caseFile.id}><div className="flex flex-col justify-between gap-4 md:flex-row"><div><div className="flex gap-2"><Badge tone={caseFile.priority === 1 ? "rose" : "amber"}>Priority {caseFile.priority}</Badge><Badge tone="mint">{percent(caseFile.confidence)} confidence</Badge></div><h2 className="mt-3 text-xl font-bold">{caseFile.title}</h2><p className="mt-2 text-sm text-slate-600">Monthly estimate <strong className="text-ink">{money(caseFile.estimated_monthly_loss)}</strong> · Annualized <strong className="text-ink">{money(caseFile.estimated_annual_loss)}</strong></p></div><FileSearch className="text-slate-300" size={28} /></div><div className="mt-5 grid gap-3 md:grid-cols-2">{caseFile.evidence.map((evidence) => <div key={evidence.id} className="rounded-xl border border-slate-100 bg-slate-50 p-4"><p className="text-sm font-bold">{titleCase(evidence.rule)}</p><p className="mt-1 text-sm leading-6 text-slate-600">{evidence.summary}</p><p className="mt-3 text-xs font-semibold text-emerald-700">Traceable amount: {money(evidence.estimated_amount)} · {evidence.record_ids.length} record(s)</p></div>)}</div>{caseFile.root_cause && <div className="mt-4 rounded-xl border border-amber-100 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><strong>Root-cause hypothesis: </strong>{caseFile.root_cause}</div>}</Card>)}{report.case_files.length === 0 && <Card>No case files were created from the supplied data.</Card>}</div>}
    {section === "Recommendations" && <div className="mt-7 grid gap-4">{report.recommendations.map((recommendation) => <Card key={recommendation.id}><div className="flex justify-between gap-3"><div><Badge tone={recommendation.priority === 1 ? "rose" : "amber"}>Priority {recommendation.priority}</Badge><h2 className="mt-3 text-lg font-bold">{recommendation.title}</h2><p className="mt-2 leading-6 text-slate-600">{recommendation.description}</p></div><ArrowUpRight className="shrink-0 text-emerald-600" /></div><p className="mt-4 text-sm font-semibold text-emerald-700">Expected monthly impact: {money(recommendation.expected_monthly_impact)}</p></Card>)}{report.recommendations.length === 0 && <Card><AlertCircle className="text-amber-600" /><p className="mt-3 font-semibold">Recommendations deferred</p><p className="mt-1 text-sm text-slate-600">Recommendations require configured LLM credentials. Case evidence remains available in the Cases view.</p></Card>}</div>}
    {section === "Executive report" && <div className="mt-7 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><Card><h2 className="text-xl font-bold">{report.executive_summary?.headline}</h2><p className="mt-4 leading-7 text-slate-600">{report.executive_summary?.summary}</p><h3 className="mt-7 font-bold">Primary root-cause hypotheses</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600">{report.executive_summary?.primary_root_causes.map((cause) => <li key={cause}>• {cause}</li>) || <li>• No LLM-generated hypotheses available.</li>}</ul><h3 className="mt-7 font-bold">Highest-priority actions</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600">{report.executive_summary?.highest_priority_actions.map((action) => <li key={action}>• {action}</li>) || <li>• No LLM-generated actions available.</li>}</ul></Card><Card><CalendarClock className="text-slate-400" /><h3 className="mt-4 font-bold">Scope limitations</h3><ul className="mt-3 space-y-3 text-sm leading-6 text-slate-600">{limitations.map((item) => <li key={item}>• {item}</li>)}</ul></Card></div>}
    {section === "Timeline" && <Card className="mt-7"><Timeline events={report.timeline} /></Card>}
  </div>;
}
